### PR TITLE
md navbar

### PR DESCRIPTION
**Pull request by djunaim**
* used bootstrap to create navbar
* used `justify-content` on `#navbarNav` to flex-end to move Home, About, Merch, and Music links to the right
* changed navbar background color to transparent

### CODE REVIEW

**Comment by aclai4067** [comment]
please update the active class on the nav for each page

**Comment by djunaim** [comment]
* updated active class for each page

**Comment by djunaim** [comment]
* added index.html to all the pages

**Comment by aclai4067** [comment]
:+1

**Pull request merged**
