### PR TITLE
Md image divs

### PR DESCRIPTION
**Pull request by djunaim**
* added images
* images are clickable and can take end user to corresponding pages, except for Upcoming Tour Dates
* removed navbar on home page as images will take its place

### CODE REVIEW

**Comment by aclai4067** [comment]
the issue dev notes mentions putting a purple border around the images that I don't see here.  Do we still want to do that?  Otherwise looks good!

**Comment by aclai4067** [comment]
actually, one more thing.  The tour dates image is smaller than the others, I think we should expand it to match

**Comment by djunaim** [comment]
had a talk with the entire group and we were ok with omitting the purple border around the images

removed padding around button to have images be the same size

**Comment by djunaim** [comment]
* added `homeImg` class to entire container of images
* updated css to only target `homeImg` `text-align`

**Comment by aclai4067** [comment]
👍

**Pull request merged**
